  spring:
    application:
      name: @project.artifactId@
    # Datasource connection properties
    datasource:
      url: ${DATASOURCE_URL:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=46189)))(CONNECT_DATA=(SERVICE_NAME=ABCPDB1)))}
      username: ${DATASOURCE_USERNAME:OT}
      password: ${DATASOURCE_PASSWORD:Orcl1234}
      driver-class-name: ${DATASOURCE_DRIVE:oracle.jdbc.OracleDriver}
      hikari:
        transaction-isolation: TRANSACTION_READ_COMMITTED
        connection-test-query: SELECT 1 FROM DUAL
        connection-init-sql: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 10
        idle-timeout: 10000
        auto-commit: false
    jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      hibernate:
        ddl-auto: ${DLL_AUTO:update}
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  server:
    port: ${SERVER_PORT:8080}

  application:
    name: ${spring.application.name}
    version: @project.version@
    description: @project.description@
